name: ElectionsPlus
version: @version@
main: me.lorenzo0111.elections.ElectionsPlus
api-version: 1.13
authors: [ Lorenzo0111, tadhunt ]
commands:
  elections:
    description: Main command
softdepend: [RealEstate, GriefPrevention, PlaceholderAPI, HolographicDisplays, DecentHolograms]